### PR TITLE
Psd 2710 ux review changes

### PR DESCRIPTION
**Pull request by tahir-khalid**
Applied changes to the UI/UX for the product create view > Upload file component.

## Description
Updated the file upload control to ensure the layout and functionality meet the design reviews.

## Screen-shots or screen-capture of UI changes

image

## Checklist:
- [X] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [X] Has acceptance criteria been tested by a peer?

### General testing (author)
- [X] Test without JavaScript
- [X] Test on small screen

### Accessibility testing (author)
- [X] Reviewed by Designer (if required)
- [X] Works keyboard only
- [X] Tested with one screen reader
- [X] Zoom page to 400% - content still visible
- [X] Disable CSS - does content make sense and appear in a logical order?

### CODE REVIEW

**Review by alan-at-work — APPROVED** [review]

**Review by meeravnagesh — APPROVED** [review]

**Comment by tahir-khalid** [comment]
PR closed for now as this is blocked and the ticket is now on the backlog (PSD-2555).

**Comment by alan-at-work** [comment]
@tahir-khalid wasn't this work was sorted by @meeravnagesh ?

**Comment by tahir-khalid** [comment]
@alan-at-work this was split into two tickets if I recall @meeravnagesh any updates on this

**Comment by meeravnagesh** [comment]
This PR is not needed anymore as we have merged the changes as a part of another PR raised by me

**Pull request closed without merging**
